Fix list-vs-set usage
See also https://github.com/alphagov/verify-terraform/pull/1271

Been getting errors like:

Error: Invalid index

  on modules/customdomain/main.tf line 36, in resource "aws_route53_record" "cert_validation":
  36:   name    = aws_acm_certificate.cert.domain_validation_options.0.resource_record_name

This value does not have any indices.